syntax = "proto2";

package mage.game.result;

option java_outer_classname = "ResultProtos";

message TableProto {
  optional MatchProto match = 1;
  optional TourneyProto tourney = 2;
  optional string game_type = 3;
  optional string deck_type = 4;
  optional string name = 5;
  optional string controller_name = 6;
  optional int64 start_time_ms = 7;
  optional int64 end_time_ms = 8;
}

message MatchProto {
  optional string name = 1;
  optional string game_type = 2;
  optional string deck_type = 3;
  optional int32 games = 4;
  optional int32 draws = 5;
  repeated MatchPlayerProto players = 6;
  optional MatchOptionsProto match_options = 7;
  optional int64 end_time_ms = 8;
}

message MatchOptionsProto {
  optional string name = 1;
  optional bool limited = 2;
  optional bool rated = 3;
  optional SkillLevel skill_level = 4;
  optional int32 wins_needed = 5;
  optional string game_type = 6;
  optional string deck_type = 7;
  optional bool multi_player = 8;
  optional string password = 9;
  optional MultiplayerAttackOption attack_option = 10;
  optional RangeOfInfluence range = 11;
  optional int32 free_mulligans = 12;
  optional bool custom_start_life_enabled = 13;
  optional int32 custom_start_life = 14;
  optional bool custom_start_hand_size_enabled = 15;
  optional int32 custom_start_hand_size = 16;
  optional bool rollback_turns_allowed = 17;
  optional bool spectators_allowed = 18;
  optional bool plane_chase = 19;
  optional int32 quit_ratio = 20;
  optional int32 minimum_rating = 21;
  optional int32 edh_power_level = 22;
  repeated string banned_users = 23;
  optional MatchTimeLimit match_time_limit = 24;
  optional MatchBufferTime match_buffer_time = 25;
  optional MulliganType mulligan_type = 26;
  repeated string player_types = 27;
}

enum MultiplayerAttackOption {
  ATTACK_MULTIPLE = 0;
  ATTACK_LEFT = 1;
  ATTACK_RIGHT = 2;
}

enum RangeOfInfluence {
  RANGE_ONE = 0;
  RANGE_TWO = 1;
  RANGE_ALL = 2;
}

enum MatchTimeLimit {
  TIME_NONE = 0;
  TIME_MIN_5 = 1;
  TIME_MIN_10 = 2;
  TIME_MIN_15 = 3;
  TIME_MIN_20 = 4;
  TIME_MIN_25 = 5;
  TIME_MIN_30 = 6;
  TIME_MIN_35 = 7;
  TIME_MIN_40 = 8;
  TIME_MIN_45 = 9;
  TIME_MIN_50 = 10;
  TIME_MIN_55 = 11;
  TIME_MIN_60 = 12;
  TIME_MIN_90 = 13;
  TIME_MIN_120 = 14;
}

enum MatchBufferTime {
  BUFFER_NONE = 0;
  BUFFER_SEC_1 = 1;
  BUFFER_SEC_2 = 2;
  BUFFER_SEC_3 = 3;
  BUFFER_SEC_5 = 4;
  BUFFER_SEC_10 = 5;
  BUFFER_SEC_15 = 6;
  BUFFER_SEC_20 = 7;
  BUFFER_SEC_25 = 8;
  BUFFER_SEC_30 = 9;
}

enum MulliganType {
  MULLIGAN_GAME_DEFAULT = 0;
  MULLIGAN_VANCOUVER = 1;
  MULLIGAN_PARIS = 2;
  MULLIGAN_LONDON = 3;
  MULLIGAN_SMOOTHED_LONDON = 4;
  MULLIGAN_CANADIAN_HIGHLANDER = 5;
}

enum SkillLevel {
  BEGINNER = 0;
  CASUAL = 1;
  SERIOUS = 2;
}

message MatchPlayerProto {
  optional string name = 1;
  optional int32 wins = 2;
  optional MatchQuitStatus quit = 3;
  optional bool bye = 4;
  optional bool human = 5;
}

enum MatchQuitStatus {
  NO_MATCH_QUIT = 0;
  IDLE_TIMEOUT = 1;  // I
  TIMER_TIMEOUT = 2;  // T
  QUIT = 3;  // Q
}

message TourneyProto {
  optional string booster_info = 1;
  repeated TourneyPlayerProto players = 2;
  repeated TourneyRoundProto rounds = 3;
}

message TourneyPlayerProto {
  optional string name = 1;
  optional string player_type = 2;
  optional string replaced_player_name = 3;
  optional TourneyQuitStatus quit = 4;
}

enum TourneyQuitStatus {
  NO_TOURNEY_QUIT = 0;
  DURING_ROUND = 1;
  DURING_DRAFTING = 2;
  DURING_CONSTRUCTION = 3;
}

message TourneyRoundProto {
  optional int32 round = 1;
  repeated MatchProto matches = 2;
  repeated string byes = 3;
}

message UserStatsProto {
  optional string name = 1;

  optional int32 tourneys = 2;
  optional int32 tourneys_quit_during_round = 3;
  optional int32 tourneys_quit_during_drafting = 4;
  optional int32 tourneys_quit_during_construction = 5;

  optional int32 matches = 6;
  optional int32 matches_idle_timeout = 7;
  optional int32 matches_timer_timeout = 8;
  optional int32 matches_quit = 9;

  optional GlickoRatingProto general_glicko_rating = 10;
  optional GlickoRatingProto constructed_glicko_rating = 11;
  optional GlickoRatingProto limited_glicko_rating = 12;
}

message GlickoRatingProto {
  required double rating = 1;
  required double rating_deviation = 2;
  optional int64 last_game_time_ms = 3;
}
